/**
 * Selects the password hash of a user account.
 *
 * @param p_cmp_id The ID of the company (safeguard).
 * @param p_usr_id The ID of the user.
 */
create procedure abc_user_password_get_hash( in p_cmp_id @aut_user.cmp_id%type@,
                                             in p_usr_id @aut_user.usr_id%type@ )
modifies sql data
-- type: singleton1
begin
	select usr_password_hash
	from   AUT_USER
	where  cmp_id = p_cmp_id
  and    usr_id = p_usr_id
	;
end
